### ISSUE TITLE
Switch to JavaFX native launcher

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej-launcher#33]
Our goal is to simplify the ImageJ launch process so we are not so intimately tied to a custom, complex launcher with its own JDK version concerns.

Perfect world goals include:
- We bundle latest Java with all the JRE-included bundles
- ImageJ options have a way for users to [point to their JRE of choice](https://github.com/imagej/imagej/issues/105)
- Users are free to still use older Java versions (i.e. 6) with an OS-agnostic no-JRE bundle
- we can easily distribute ImageJ, [without requiring the Fiji update site](https://github.com/imagej/imagej/issues/118)

JavaFX is currently our first choice for deployment. It appears to be capable of building standalone (no bundled JRE) and self-contained (bundled JRE) apps cross-platform. These is also a [maven plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin)

JavaFX issues that need to be solved:
- [x] Not able to set `<fx:platform basedir=""/>` to get standalone deployment. **SOLVED** by using build.xml. See also javafx-maven-plugin/javafx-maven-plugin#127.
- [x] `jfx:native` goal doesn't respect app name configuration. **SOLVED** - see javafx-maven-plugin/javafx-maven-plugin#128.
- [x] Preloaders. **WONTUSE** preloaders live in the same JVM as the application. They will not meet our needs.
- [ ] Command line arguments - we need to be able to support things like `--debugger=8000` which the native launcher translated to JVM argument(s). See [SO #30809330](http://stackoverflow.com/q/30809330).
- [ ] Figure out how we want to handle updating. This is tied to the [refresh menus](https://github.com/imagej/ij1-patcher/issues/31) problem. It sounds like the `.jar` lock in Windows may be fixed in Java 7 allowing runtime swapping, in which case checking for updates at startup and replacing `.jars` before loading classes and spinning up a context may be an option worth investigating, especially if we remove the `ImageJ` update site - which would become an immutable `/lib`.
- [ ] We need a splash screen. Options would be using `java -splash` or JavaFX.
- [ ] To test: what happens if you try running a no-JRE JFX distribution on a platform without Java installed?
# Platform-specific notes
## Linux
- Debian bundler requires `fakeroot` to be installed and just fails if it isn't. This will only affect developer machines though.
- Native launcher produced by debian bundler fails with no packaged JRE (message complains that JRE can't be found)
## Windows
- Install WiX (wixtoolset.org) - **Version 3.X**
- Install Inno Setup jrsoftware.org/isdl.php
- Had to fix classpath (didn't have to on linux/osx)
- `exe` installer installed to `C:\Users\username\AppData\Local\ImageJ`
- `msi` installer installed to `C:\Program Files\ImageJ`
- icon works except it's lost on the app for .exe installer

**Comment by hinerm** [comment]
[JavaFX](http://docs.oracle.com/javase/8/docs/technotes/guides/deploy/self-contained-packaging.html#BCGIGHHC) may solve this issue

**Comment by hinerm** [comment]
However, we need to document what features we may be losing from migrating to JavaFX..

**Comment by hinerm** [comment]
Note that whatever solution we settle on we also should ensure our Java3D problems are solved forever and ever.

@ctrueden has a fork of Java 3D 1.6 that is Mavenized.. that may be sufficient..

**Comment by ctrueden** [comment]
JavaFX provides a developer-facing API for controlling which parameters go to the JVM (e.g., memory settings). Devs can write code letting users set these in their UI of choice, and propagate the information to the JavaFX launcher in a platform-agnostic way (uses Java Prefs API internally). See [UserJvmOptionsService API docs](http://docs.oracle.com/javase/8/docs/technotes/guides/deploy/jvm_options_api.html) for details.

**Comment by ctrueden** [comment]
Experimental [javafx branch](https://github.com/imagej/imagej/compare/javafx) can create standalone app (i.e., a double-clickable JAR file which leans on the installed system JRE) as well as a self-contained app (i.e., an app which bundles its own JRE).

Unfortunately, there is no middle ground in JavaFX by default: you cannot have an app (e.g., EXE on Windows, .app bundle on OS X, etc.) which does not bundle a JRE.

Or _[can you](https://blogs.oracle.com/talkingjavadeployment/entry/packaging_improvements_in_jdk_7#2]_? This would be great so that users still get JRE security updates without it being ImageJ's responsibility.

**Comment by ctrueden** [comment]
I updated the javafx branch in an attempt to use a custom preloader, but it doesn't work yet.

To test things at a lower level—and also to test the `<fx:platform basedir=""/>` hack for creating a self-contained app without JRE—it is probably time to start calling the Ant tasks directly. Once those are working, we can debug into the `javafx-maven-plugin` to figure out how to enhance/fix it accordingly.

**Comment by ctrueden** [comment]
I tested the `<fx:platform basedir=""/>` thing to create a self-contained bundle sans JRE, and it works. Hooray!

This might not actually be the direction we want to go, but it is nice to know we can do it.

Now, we just have to fully understand preloaders...

**Comment by hinerm** [comment]
Added javafx-maven-plugin issues:

* https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/127
* TODO - jfxMainAppJarName problems

**Comment by FibreFoX** [comment]
>  Preloaders. WONTUSE preloaders live in the same JVM as the application. They will not meet our needs.

Just my two cents: preloaders are not fully supported on native app launchers, but can be archived by other ways (I noted it down [here](https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/80))

You could create that kind of "splash-screens" as first stage and just switching when ready (like proposed as [solution 5 at stackoverflow](http://stackoverflow.com/questions/15126210/how-to-use-javafx-preloader-with-stand-alone-application-in-eclipse))

**Comment by FibreFoX** [comment]
Hi, just wanted to inform you guys about a pull-request I made for supporting `UserJvmOptionsService` via javafx-maven-plugin, [here is the issue-ticket](https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/136) about it, maybe you want to try this out (just checked back, because i remembered you thinking about using that API).

Hopefully you don't see this as spamming ;)

**Comment by ctrueden** [comment]
@FibreFoX Thanks for the heads up, and for your great responsiveness in general. :smile: Will try to process and review the linked issue later this month.

**Comment by ctrueden** [comment]
Reminder to myself: when progress is made on this issue, follow up on [Fiji bug #933](http://fiji.sc/bugzilla/show_bug.cgi?id=933) with a link to a JavaFX-based Fiji application bundle, for Antonio Sechi to try out.

**Comment by FibreFoX** [comment]
> To test: what happens if you try running a no-JRE JFX distribution on a platform without Java installed?

When the bundle does not contain the stripped JRE (which is generated by the javafx-bundler itself), the generated `.cfg`-file contains an "empty" entry `app.runtime=`, [which can be seen here](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinAppBundler.java#L403). Running the native launcher will search for the `.cfg`-file, if there was something specified, that path will be taken as JRE-root, [which can be found here](https://github.com/Debian/openjfx/blob/master/modules/fxpackager/src/main/native/library/common/Package.cpp#L133). I crossed these files while bugtracking [issue 124](https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/124). This means, that when not having the runtime bundled, at least on windows-systems, the local installed version will be taken (which might reduce the size of the bundle, but increases problems with not-tested java-versions, or outdated ones...)

There still is some problem which I found just right now with the javafx-maven-plugin: normal way for me was to specify an empty setting:
```
<bundleArguments>
    <runtime />
</bundleArguments>
```
But the resulting .cfg-file still containes the wrong line. This is something, I will fix in the next days.


> Command line arguments - we need to be able to support things like --debugger=8000 which the native launcher translated to JVM argument(s).

For the debugger-thing, maybe you want to create multiple native launchers, this feature is available with normal ant-version of java(fx)bundler and will come in the next days (I'm already developing this feature). All CLI-arguments can be passed normally (and accessed in the main-method, [there exists a IT-project for this](https://github.com/javafx-maven-plugin/javafx-maven-plugin/tree/master/src/it/09-withPackagerJar)), but to activate special java-properties I suggest to have multiple pre-configured launchers. Maybe it'll work to have UserJvmOptionsService for this instead of different native launchers, this is supported by putting the packager.jar as system-scoped dependency to your project, [like in this IT-project](https://github.com/javafx-maven-plugin/javafx-maven-plugin/tree/master/src/it/11-access-application-and-jvm-parameters) (not nice, but working). All in all these ways might remove the need of own native launchers.

**Comment by ctrueden** [comment]
Thanks @FibreFoX. All the links in particular are very helpful and much appreciated.

We are increasingly leaning toward always bundling a JRE in the platform-specific distributions, for the reasons you mention. We want to ship the app via modern "blessed" distribution mechanisms such as the App Store on OS X, to make our users' lives easier. So at least on OS X we would need to bundle a JRE anyway.

Regarding multiple native launchers: my current thinking is to have one native launcher with sensible defaults and configurability via the UserJvmOptionsService... and then one shell script launcher for developers which provides total customizability—e.g., launching with a debug port open. I cannot come up with a use case for non-developer users where specifying the desired JVM flags in a UI window, and then restarting, isn't good enough.

**Comment by FibreFoX** [comment]
> Native launcher produced by debian bundler fails with no packaged JRE (message complains that JRE can't be found)

This might be since java 1.8.0 update 60, [see the issue on javafx-maven-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/167), this got a workaround in latest snapshot-version (had this problem on windows too)

>  exe installer installed to C:\Users\username\AppData\Local\ImageJ 
>  msi installer installed to C:\Program Files\ImageJ 

This can be changed by modifying the generated installer-file (wsx), which is placed under some temporary folder, will be shown/reported, when javafx-maven-plugin contains `<verbose>true</verbose>`, same goes for msi-installer. In current JDK there seems to exist specific one bundleArgument to make installation-target selectable, but haven't tried it yet; bundle argument for both: [exe-bundler](http://hg.openjdk.java.net/openjfx/8u60/rt/file/996511a322b7/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinExeBundler.java#l469) and [msi-bundler](http://hg.openjdk.java.net/openjfx/8u60/rt/file/996511a322b7/modules/fxpackager/src/main/java/com/oracle/tools/packager/windows/WinMsiBundler.java#l676):
```
<bundleArgument>
<installdirChooser>true</installdirChooser>
</bundleArgument>
```

**Comment by FibreFoX** [comment]
For the splash-screen, because I don't want to have preloader-magic, I'm using some launcher-class which encapsulates some heavier calculationparts while showing slashscreen. [I've created a GIST about this already](https://gist.github.com/FibreFoX/294012b16fa10519674b) which is free to use, but might not be the best solution. The reason I took that approach: Showing some messsages while loading user-settings or processing some signals which are business-logic, which does not fit into normal "splash-screen"-logic.

**Comment by FibreFoX** [comment]
:smile: oh, and sorry for spamming your thread here

**Comment by ctrueden** [comment]
Apparently there is now a Java Packager which is (will become?) part of Java 12.

Here is an article discussing it:
https://medium.com/@adam_carroll/java-packager-with-jdk11-31b3d620f4a8

So the Java Packager will need to be evaluated as well, as part of this work.
